# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rby1_right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_right_gripper_controller:
      type: position_controllers/GripperActionController


    rby1_left_gripper_controller:
      type: position_controllers/GripperActionController


    rby1_dualarm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rby1_wholebody_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rby1_right_arm_controller:
  ros__parameters:
    joints:
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
rby1_left_arm_controller:
  ros__parameters:
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
rby1_torso_controller:
  ros__parameters:
    joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
rby1_right_gripper_controller:
  ros__parameters:
    joint: gripper_finger_r1
rby1_left_gripper_controller:
  ros__parameters:
    joint: gripper_finger_l1
rby1_dualarm_controller:
  ros__parameters:
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
rby1_head_controller:
  ros__parameters:
    joints:
      - head_0
      - head_1
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
rby1_wholebody_controller:
  ros__parameters:
    joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
      - head_0
      - head_1
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity